CREATE TABLE DEPT (
DEPTNO NUMBER(5),
DNAME VARCHAR2(50),
LOC VARCHAR2(50),
CONSTRAINT dept_pk PRIMARY KEY (DEPTNO) ,
CONSTRAINT dept_ck CHECK ( DNAME IN ( 'ACCOUNTING', 'RESEARCH', 'SALES','OPERATIONS' )));

INSERT INTO DEPT VALUES (10,'ACCOUNTING','New-York');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP AS SELECT * FROM SCOTT.EMP;

INSERT INTO EMP VALUES (7369, 'Bidon', NULL, NULL, NULL, NULL, NULL, NULL) ;

ROLLBACK ;

ALTER TABLE EMP ADD CONSTRAINT emp_pk PRIMARY KEY (EMPNO);
ALTER TABLE EMP ADD CONSTRAINT emp_fk FOREIGN KEY (DEPTNO) REFERENCES Dept(DEPTNO);


INSERT INTO EMP VALUES (7369, 'WILSON', 'MANAGER', 7839, TO_DATE('17/11/91','dd/mm/yy'), 3500.00, 600.00, 10) ;
INSERT INTO EMP VALUES(7657, 'WILSON','MANAGER', 7839,  TO_DATE('17/11/91','dd/mm/yy'), 3500.00, 600.00, 50) ;
INSERT INTO EMP VALUES(7657, 'WILSON', 'MANAGER', 7000, TO_DATE('17/11/91','dd/mm/yy'), 3500.00, 600.00, 10) ;
INSERT INTO EMP VALUES (7657, 'WILSON', 'MANAGER', 7839,  TO_DATE('17/11/91','dd/mm/yy'), 3500.00,600.00, 10);

commit;

ALTER TABLE DEPT SET LOC='PITTSBURGH' WHERE DNAME='SALES';

ALTER TABLE EMP SET SAL=SAL*1.10
where comm>SAL/2;

ALTER TABLE EMP SET COMM=avg(nvl(comm,0))
WHERE hire_date < TO_DATE( '01/01/82','dd/mm/yy') AND COMM IS NULL ;

DELETE FROM DEPT WHERE DEPTNO=20;




Select ENAME,sal,comm,sal+comm
FROM emp
WHERE JOB='SALESMAN';


SELECT ename
FROM emp
order by comm/sal;


SELECT ename
FROM emp
WHERE comm < sal/4;


SELECT COUNT(*)
FROM emp
WHERE DEPTNO=10;    

SELECT COUNT(*)
FROM emp
WHERE comm IS NOT NULL;


SELECT DISTINCT job
FROM emp;


SELECT job,AVG(sal)
FROM emp
GROUP BY job;


SELECT SUM(sal)
FROM emp
WHERE deptno = (SELECT deptno FROM dept WHERE dname = 'SALES');


SELECT ename,dname
FROM emp e, dept d
WHERE e.deptno = d.deptno;


SELECT ename,job,sal
FROM emp
WHERE sal = (SELECT MAX(sal) FROM emp);

SELECT ename
FROM emp 
WHERE sal > (SELECT sal FROM emp WHERE ename='JONES');

SELECT ENAME FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME='JONES');

select ename from emp  where mgr=(SELECT mgr from emp where ename='CLARK');


select ename , job from emp where MGR =(SELECT MGR FROM EMP WHERE ENAME='TURNER')
AND JOB= (SELECT JOB FROM EMP WHERE ENAME ='TURNER');


SELECT ENAME FROM EMP WHERE hiredate<ALL(SELECT hiredate FROM EMP WHERE DEPTNO=10);


SELECT e.ename , w.ename
from emp e , emp w
where e.empno=w.empno ;

SELECT e.ename
FROM EMP e , EMP w
WHERE e.empno = w.empno and e.deptno<>w.deptno;